"""adds Country table

Revision ID: 2dbae8a3e461
Revises: dddf68ad1082
Create Date: 2018-09-30 13:38:49.329770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbae8a3e461'
down_revision = 'dddf68ad1082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isoa2', sa.String(length=6), nullable=False),
    sa.Column('isoa3', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isoa2'),
    sa.UniqueConstraint('isoa3'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'event', sa.Column('language', sa.String(length=5), nullable=True))
    op.add_column(u'location', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'location', 'language')
    op.drop_column(u'event', 'language')
    op.drop_table('country')
    # ### end Alembic commands ###
