"""Add event description

Revision ID: a78efda46903
Revises: 26a906c33026
Create Date: 2018-09-06 12:29:33.385253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78efda46903'
down_revision = '26a906c33026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('desc', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'desc')
    # ### end Alembic commands ###
