"""Location table

Revision ID: dddf68ad1082
Revises: a78efda46903
Create Date: 2018-09-21 19:02:03.950437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dddf68ad1082'
down_revision = 'a78efda46903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('added_ts', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    op.add_column(u'event', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column(u'event', sa.Column('location_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'event', 'location', ['location_id'], ['id'])
    op.drop_column(u'event', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'event', sa.Column('location', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column(u'event', 'location_name')
    op.drop_column(u'event', 'location_id')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
